//============================================================================
//  SlopperPI - Seibu SPI / SXX2E
//
//  ROM loader: streams the MRA's concatenated ROM image from ioctl into SDRAM,
//  performing the MAME ROM_LOAD24_* / ROM_LOAD32_* scatter in hardware.
//
//  MRA <interleave> cannot express a 3-byte period, which is exactly what the
//  Seibu "D + P" graphics ROM pairs need: two ROMs supply bytes 0 and 1 of each
//  3-byte group and a third supplies byte 2. So the MRA just concatenates the
//  raw files in a fixed order and this module places every byte.
//
//  NOTE on the 24-bit word mode: MAME's ROM_GROUPWORD swaps the two bytes of
//  each source word when the destination is a plain ROM_REGION, as "chars" and
//  "tiles" are. The 32-bit modes do NOT swap, because "maincpu" is declared
//  ROM_REGION32_LE. This was verified by comparing tools/build_sdram_image.py's
//  output against MAME's own :maincpu region (byte exact) and against its
//  decrypted :chars and :tiles regions (exact after decryption).
//
//  One 16-bit masked SDRAM write per input byte. That caps the loader at about
//  14 MB/s, at or above what the HPS delivers over ioctl, so merging adjacent
//  bytes into single writes would not measurably help.
//
//  Every byte passes through spi_rom_decode on the way, so a part can be
//  DECODED rather than copied -- rdft2's sample flash is generated by a
//  decompressor, not concatenated out of ROMs, so no MRA can assemble it. A
//  decoded part breaks the 1:1 rule the rest of this module assumed: `in_off`
//  counts bytes ARRIVING (it is what ends the part, and what part_size means)
//  while `out_off` counts bytes EMITTED (it is what the scatter addresses).
//  For CODEC_RAW parts the two run in lockstep and nothing changes.
//============================================================================

module rom_loader
(
	input             clk,
	input             reset,

	// ioctl (index 0 = MRA ROM image)
	input             ioctl_download,
	input             ioctl_wr,
	input       [7:0] ioctl_index,
	input       [7:0] ioctl_dout,
	output reg        ioctl_wait,

	// Which part table to walk: SET_RDFTS / SET_RDFT / SET_RDFT2, decoded in
	// SeibuSPI.sv from the MRA's index-1 mod byte. It must be stable before the
	// index-0 download starts, which it is: the HPS sends the mod byte first.
	input       [1:0] set_id,

	// Codec per part, 4 bits each, part 0 in the low nibble. Comes from the
	// MRA's index-1 config the same way set_id does, and is all zero
	// (CODEC_RAW) unless the MRA says otherwise. See rtl/spi_rom_decode.sv.
	input      [63:0] part_codec,

	// SDRAM write port (channel 3, toggle handshake)
	output reg [25:0] sdr_addr,
	output reg [15:0] sdr_din,
	output reg  [1:0] sdr_be,
	output reg        sdr_req,
	output reg        sdr_rnw,
	input             sdr_ack,

	output reg        rom_ready,

	// Telemetry. The ioctl download is the one path that cannot be simulated,
	// so count what actually arrived: bytes_in should end at 23,396,352 for
	// rdfts, and part_end at the last part index. Anything less means the HPS
	// flow control dropped data and every part after the gap is misplaced.
	// bytes_out is what reached SDRAM; it differs from bytes_in only when a
	// part is decoded, and then by exactly the expansion.
	output reg [25:0] bytes_in,
	output reg [25:0] bytes_out,
	output reg  [3:0] part_end
);

`include "spi_defs.vh"

	// ------------------------------------------------------------------
	// Scatter modes
	// ------------------------------------------------------------------
	localparam [3:0] M_LINEAR  = 4'd0;   // dest = base + i
	localparam [3:0] M_32_B0   = 4'd1;   // dest = base + i*4 + 0
	localparam [3:0] M_32_B1   = 4'd2;   // dest = base + i*4 + 1
	localparam [3:0] M_32_B2   = 4'd3;   // dest = base + i*4 + 2
	localparam [3:0] M_32_B3   = 4'd4;   // dest = base + i*4 + 3
	localparam [3:0] M_32_W01  = 4'd5;   // dest = base + (i>>1)*4 + 0 + (i&1)
	localparam [3:0] M_32_W23  = 4'd6;   // dest = base + (i>>1)*4 + 2 + (i&1)
	localparam [3:0] M_24_B0   = 4'd7;   // dest = base + i*3 + 0
	localparam [3:0] M_24_B1   = 4'd8;   // dest = base + i*3 + 1
	localparam [3:0] M_24_B2   = 4'd9;   // dest = base + i*3 + 2
	localparam [3:0] M_24_W01  = 4'd10;  // dest = base + (i>>1)*3 + (1 - (i&1))
	// LINEAR, plus MAME's sprite_reorder() rotated into the destination: within
	// each 64-byte group the 32 words are permuted so that output word 2j comes
	// from input word j and output word 2j+1 from input word j+16. As an index
	// that is one rotate -- dest = {i[5:0] rotated left by one word}.
	//
	// This is a LOAD-time permutation in a project whose rule is that graphics
	// decryption happens at FETCH time (PLAN.md 5), and deliberately so.
	// sprite_reorder is not decryption, it is an address swizzle, and doing it
	// here is free: the loader computes a destination per byte regardless.
	// Doing it at fetch time is not free -- it puts the two halves of a 16-pixel
	// row 32 bytes apart instead of 2, so a row would cost six SDRAM reads
	// instead of three, doubling sprite bandwidth on the one set that already
	// has the most sprite data.
	localparam [3:0] M_SPR_R10 = 4'd11;

	// Part indices are 4 bits, and part_end (which spi_jtag_peek reports by bit
	// position) is 4 bits with it. That is the reason rdft2's six sprite ROMs
	// are ONE loader part rather than six: at a 6 MB chunk stride they are
	// contiguous from SDR_SPRITES_BASE, so one LINEAR run places all of them,
	// and 19 parts would not have fit. check_mra.py still checks all six
	// individually, by walking that part's MRA members.
	localparam [3:0] NPARTS_RDFTS = 4'd14;
	localparam [3:0] NPARTS_RDFT  = 4'd15;
	localparam [3:0] NPARTS_RDFT2 = 4'd14;

	reg [3:0] nparts;
	always @* case (set_id)
		SET_RDFT : nparts = NPARTS_RDFT;
		SET_RDFT2: nparts = NPARTS_RDFT2;
		default  : nparts = NPARTS_RDFTS;
	endcase

	// ------------------------------------------------------------------
	// Part tables. The order in each must match the <part> order in the MRA,
	// and tools/check_mra.py checks exactly that against MAME's driver --
	// nothing at runtime can, because the MRA carries no scatter information.
	// A case statement rather than a parameter array: Quartus 17.0 handles
	// unpacked-array parameters unevenly.
	//
	// SXX2C differs more than it looks. Its 386 program is four byte-lanes
	// instead of two bytes plus a word, its text layer is three byte-lanes
	// instead of a word plus a byte, and it has NO Z80 part at all -- that
	// region is RAM the 386 fills through port 0x688 before releasing the Z80
	// from reset. The sample part is the pre-programmed flash image the MRA
	// assembles from the cartridge's own sound ROMs, and `sound01` is absent:
	// measured, the 386 never reads that window once the flash is programmed
	// (section 0).
	// ------------------------------------------------------------------
	reg [3:0]  part;
	reg [25:0] in_off;     // bytes of this part taken from ioctl
	reg [25:0] out_off;    // bytes of this part emitted into SDRAM

	reg [25:0] part_base;
	reg [25:0] part_size;
	reg [3:0]  part_mode;

	always @* begin
		case (set_id)

		// ---- TABLE rdft: SPI cartridge, pre-flashed (SXX2C) ----
		SET_RDFT: case (part)
			//                                          base   size          mode
			4'd0 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B0;  end // raiden-fi_prg0_121196.u0211
			4'd1 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B1;  end // raiden-fi_prg1_121196.u0212
			4'd2 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B2;  end // raiden-fi_prg2_121196.u0210
			4'd3 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B3;  end // raiden-fi_prg3_121196.u029
			4'd4 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B0;  end // seibu_5.u0423
			4'd5 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B1;  end // seibu_6.u0424
			4'd6 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B2;  end // seibu_7.u048
			4'd7 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg1-d.u0415
			4'd8 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg1-p.u0410
			4'd9 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg2-d.u0424
			4'd10: begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg2-p.u049
			4'd11: begin part_base = SDR_SPRITES_BASE;                   part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-1.u0322
			4'd12: begin part_base = SDR_SPRITES_BASE +   SPR_CHUNK_STRIDE;  part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-2.u0324
			4'd13: begin part_base = SDR_SPRITES_BASE + 2*SPR_CHUNK_STRIDE;  part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-3.u0323
			default:begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // pre-programmed flash image
		endcase

		// ---- TABLE rdft2: SPI cartridge, decoded sample flash (SXX2C) ----
		//
		// Differences from rdft, all read off MAME's ROM_START(rdft2):
		//   * twice the tiles (12 MB), so the second bg group sits at +6 MB
		//   * text lanes come in the order fix0(1), fix1(0), fixp(2)
		//   * 18 MB of sprites as three 6 MB plane-pair chunks, which are
		//     contiguous and so load as ONE part -- obj3 first, then obj2,
		//     then obj1, which is MAME's order and not the numeric one. It is
		//     M_SPR_R10, not M_LINEAR: RISE10 sets carry sprite_reorder()
		//   * the sample flash is two parts: the region stamp plus a verbatim
		//     slice of pcm.u0217, then sound1.u0222 COMPRESSED. The MRA marks
		//     that last part CODEC_BPE_DPCM, so its size here is the
		//     compressed length -- 0x4C665 in, 0x730ED out (PLAN.md 0).
		SET_RDFT2: case (part)
		//                                                    base   size          mode
		4'd0 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B0;  end // prg0.tun
		4'd1 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B1;  end // prg1.bin
		4'd2 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B2;  end // prg2.bin
		4'd3 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B3;  end // prg3.bin
		4'd4 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B1;  end // fix0.u0524
		4'd5 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B0;  end // fix1.u0518
		4'd6 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B2;  end // fixp.u0514
		4'd7 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h040_0000; part_mode = M_24_W01; end // bg-1d.u0535
		4'd8 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h020_0000; part_mode = M_24_B2;  end // bg-1p.u0537
		4'd9 : begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h040_0000; part_mode = M_24_W01; end // bg-2d.u0536
		4'd10: begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h020_0000; part_mode = M_24_B2;  end // bg-2p.u0538
		4'd11: begin part_base = SDR_SPRITES_BASE;                  part_size = 26'h120_0000; part_mode = M_SPR_R10; end // sprites: obj3 obj3b obj2 obj2b obj1 obj1b
		4'd12: begin part_base = SDR_PCM_BASE;                      part_size = 26'h017_C247; part_mode = M_LINEAR; end // flash head: region stamp + pcm.u0217
		default:begin part_base = SDR_PCM_BASE + 26'h017_C247;      part_size = 26'h004_C665; part_mode = M_LINEAR; end // flash tail: sound1.u0222 compressed
		endcase

		// ---- TABLE rdfts: SXX2E single board ----
		default: case (part)
			//                                          base   size          mode
			4'd0 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B0;  end // seibu_1.u0259
			4'd1 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B1;  end // raiden-f_prg2.u0258
			4'd2 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h010_0000; part_mode = M_32_W23; end // raiden-f_prg34.u0262
			4'd3 : begin part_base = SDR_Z80_BASE;                       part_size = 26'h002_0000; part_mode = M_LINEAR; end // seibu_zprg.u1139
			4'd4 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h002_0000; part_mode = M_24_W01; end // raiden-f_fix.u0535
			4'd5 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B2;  end // seibu_fix2.u0528
			4'd6 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg1-d.u0526
			4'd7 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg1-p.u0531
			4'd8 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg2-d.u0534
			4'd9 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg2-p.u0530
			4'd10: begin part_base = SDR_SPRITES_BASE;                   part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-1.u0322
			4'd11: begin part_base = SDR_SPRITES_BASE +   SPR_CHUNK_STRIDE;  part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-2.u0324
			4'd12: begin part_base = SDR_SPRITES_BASE + 2*SPR_CHUNK_STRIDE;  part_size = 26'h040_0000; part_mode = M_LINEAR; end // gun_dogs_obj-3.u0323
			default:begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // raiden-f_pcm2.u0975
		endcase

		endcase
	end

	wire last_part = (part == nparts - 4'd1);

	// Destination offset within the part, per scatter mode. This indexes
	// EMITTED bytes: for a decoded part the source offset is not the
	// destination offset, and it is the output that has to land in order.
	wire [25:0] off   = out_off;
	wire [25:0] off_h = {1'b0, out_off[25:1]};   // off >> 1
	reg [25:0] scat;
	always @* begin
		// Every term is written out at the full 26 bits. These used to be sized
		// by hand for a 25-bit address and each one needed a different patch
		// when the map grew; `off_h` exists so the halved forms cannot drift
		// from each other again.
		case (part_mode)
			M_LINEAR: scat =  off;
			M_32_B0 : scat = {off[23:0], 2'b00};
			M_32_B1 : scat = {off[23:0], 2'b00} + 26'd1;
			M_32_B2 : scat = {off[23:0], 2'b00} + 26'd2;
			M_32_B3 : scat = {off[23:0], 2'b00} + 26'd3;
			M_32_W01: scat = {off_h[23:0], 2'b00}         + {25'd0, off[0]};
			M_32_W23: scat = {off_h[23:0], 2'b00} + 26'd2 + {25'd0, off[0]};
			M_24_B0 : scat = {off[24:0], 1'b0} + off;
			M_24_B1 : scat = {off[24:0], 1'b0} + off + 26'd1;
			M_24_B2 : scat = {off[24:0], 1'b0} + off + 26'd2;
			M_24_W01: scat = {off_h[24:0], 1'b0} + off_h + {25'd0, ~off[0]};
			M_SPR_R10: scat = {off[25:6], off[4:1], off[5], off[0]};
			default : scat =  off;
		endcase
	end

	wire [25:0] dest = part_base + scat;

	// ------------------------------------------------------------------
	// Decoder
	// ------------------------------------------------------------------
	// One byte of skid between ioctl and the decoder. The previous loader
	// consumed ioctl_wr in the cycle it arrived and silently DROPPED the byte
	// if a write was in flight; ioctl_wait has a cycle of latency, so that only
	// ever worked because the HPS is slower than the SDRAM. A decoded part
	// stalls for hundreds of cycles, so hold the byte instead of losing it.
	reg       hold_valid;
	reg [7:0] hold_data;

	wire       dec_in_ready, dec_out_valid, dec_idle;
	wire [7:0] dec_out_data;

	reg  busy;
	reg  part_step;      // one cycle at each part boundary, arms the decoder
	reg  dl_d;

	wire download = ioctl_download && (ioctl_index == 8'd0);

	// The part's input is spent. What ends a part is bytes IN, not bytes out:
	// a decoded part's output length is a property of the data, not the table.
	wire part_in_full = (in_off == part_size);
	wire feed         = hold_valid && !part_in_full && dec_in_ready;
	wire emit         = dec_out_valid && !busy;
	wire part_done    = part_in_full && dec_idle && !busy;

	wire [3:0] codec = part_codec[{part, 2'b00} +: 4];

	spi_rom_decode decode
	(
		.clk       (clk),
		.reset     (reset),
		.codec     (codec),
		.start     ((download && !dl_d) || part_step),
		.in_valid  (hold_valid && !part_in_full),
		.in_data   (hold_data),
		.in_ready  (dec_in_ready),
		.out_valid (dec_out_valid),
		.out_data  (dec_out_data),
		.out_ready (emit),
		.idle      (dec_idle)
	);

	// ------------------------------------------------------------------
	// Write sequencing
	// ------------------------------------------------------------------
	reg seen_download;   // rom_ready must not assert before the first download

	always @(posedge clk) begin
		if (reset) begin
			part          <= 4'd0;
			in_off        <= 26'd0;
			out_off       <= 26'd0;
			busy          <= 1'b0;
			ioctl_wait    <= 1'b0;
			sdr_req       <= 1'b0;
			sdr_rnw       <= 1'b1;
			rom_ready     <= 1'b0;
			seen_download <= 1'b0;
			hold_valid    <= 1'b0;
			part_step     <= 1'b0;
			dl_d          <= 1'b0;
			bytes_in      <= 26'd0;
			bytes_out     <= 26'd0;
			part_end      <= 4'd0;
		end
		else begin
			part_step <= 1'b0;
			dl_d      <= download;

			// A write retires when ack catches up with req.
			if (busy && (sdr_ack == sdr_req)) busy <= 1'b0;

			// Emitting is deliberately outside the `download` arm: a decoded
			// part is still draining after the HPS drops ioctl_download, and
			// those bytes are as real as the rest.
			if (emit) begin
				sdr_addr  <= {dest[25:1], 1'b0};
				sdr_din   <= {dec_out_data, dec_out_data};
				sdr_be    <= dest[0] ? 2'b10 : 2'b01;
				sdr_rnw   <= 1'b0;
				sdr_req   <= ~sdr_req;
				busy      <= 1'b1;
				out_off   <= out_off + 26'd1;
				bytes_out <= bytes_out + 26'd1;
			end

			if (feed) begin
				hold_valid <= 1'b0;
				ioctl_wait <= 1'b0;
				in_off     <= in_off + 26'd1;
			end

			if (part_done) begin
				in_off    <= 26'd0;
				out_off   <= 26'd0;
				part_step <= 1'b1;
				if (!last_part) part <= part + 4'd1;
			end

			if (download) begin
				seen_download <= 1'b1;
				rom_ready     <= 1'b0;
				part_end      <= part;

				// Capture last so a byte arriving in the same cycle the held
				// one is consumed replaces it rather than being dropped.
				if (ioctl_wr) begin
					bytes_in   <= bytes_in + 26'd1;
					hold_data  <= ioctl_dout;
					hold_valid <= 1'b1;
					ioctl_wait <= 1'b1;
				end
			end
			else begin
				// Image is in place once the decoder has drained and the last
				// write has retired.
				if (!busy && dec_idle && !hold_valid) begin
					if (seen_download) rom_ready <= 1'b1;
					part    <= 4'd0;
					in_off  <= 26'd0;
					out_off <= 26'd0;
				end
			end
		end
	end

endmodule
