//============================================================================
//  SlopperPI - Seibu SPI / SXX2E
//
//  ROM loader: streams the MRA's concatenated ROM image from ioctl into SDRAM,
//  performing the MAME ROM_LOAD24_* / ROM_LOAD32_* scatter in hardware.
//
//  MRA <interleave> cannot express a 3-byte period, which is exactly what the
//  Seibu "D + P" graphics ROM pairs need: two ROMs supply bytes 0 and 1 of each
//  3-byte group and a third supplies byte 2. So the MRA just concatenates the
//  raw files in a fixed order and this module places every byte.
//
//  NOTE on the 24-bit word mode: MAME's ROM_GROUPWORD swaps the two bytes of
//  each source word when the destination is a plain ROM_REGION, as "chars" and
//  "tiles" are. The 32-bit modes do NOT swap, because "maincpu" is declared
//  ROM_REGION32_LE. This was verified by comparing tools/build_sdram_image.py's
//  output against MAME's own :maincpu region (byte exact) and against its
//  decrypted :chars and :tiles regions (exact after decryption).
//
//  One 16-bit masked SDRAM write per input byte. That caps the loader at about
//  14 MB/s, at or above what the HPS delivers over ioctl, so merging adjacent
//  bytes into single writes would not measurably help.
//
//  Every byte passes through spi_rom_decode on the way, so a part can be
//  DECODED rather than copied -- rdft2's sample flash is generated by a
//  decompressor, not concatenated out of ROMs, so no MRA can assemble it. A
//  decoded part breaks the 1:1 rule the rest of this module assumed: `in_off`
//  counts bytes ARRIVING (it is what ends the part, and what part_size means)
//  while `out_off` counts bytes EMITTED (it is what the scatter addresses).
//  For CODEC_RAW parts the two run in lockstep and nothing changes.
//============================================================================

module rom_loader
(
	input             clk,
	input             reset,

	// ioctl (index 0 = MRA ROM image)
	input             ioctl_download,
	input             ioctl_wr,
	input       [7:0] ioctl_index,
	input       [7:0] ioctl_dout,
	output reg        ioctl_wait,

	// Which part table to walk: SET_RDFTS / SET_RDFT / SET_RDFT2 / SET_RFJET,
	// decoded in SeibuSPI.sv from the MRA's index-1 mod byte. It must be
	// stable before the
	// index-0 download starts, which it is: the HPS sends the mod byte first.
	input       [2:0] set_id,

	// The authentic-flash variant of a cartridge set: the same head of the
	// table, a different tail. Instead of a finished sample-flash image the MRA
	// carries a BLANK flash and the two sound ROMs the game's own updater reads
	// to program it. mod byte bit 4; PLAN.md section 17.
	input             set_upd,

	// Codec per part, 4 bits each, part 0 in the low nibble, 32 parts. Comes
	// from the MRA's index-1 config the same way set_id does, and is all zero
	// (CODEC_RAW) unless the MRA says otherwise. See rtl/spi_rom_decode.sv.
	input     [127:0] part_codec,

	// SDRAM write port (channel 3, toggle handshake)
	output reg [25:0] sdr_addr,
	output reg [15:0] sdr_din,
	output reg  [1:0] sdr_be,
	output reg        sdr_req,
	output reg        sdr_rnw,
	input             sdr_ack,

	output reg        rom_ready,

	// Telemetry. The ioctl download is the one path that cannot be simulated,
	// so count what actually arrived: bytes_in should end at 23,396,352 for
	// rdfts, and part_end at the last part index. Anything less means the HPS
	// flow control dropped data and every part after the gap is misplaced.
	// bytes_out is what reached SDRAM; it differs from bytes_in only when a
	// part is decoded, and then by exactly the expansion.
	output reg [25:0] bytes_in,
	output reg [25:0] bytes_out,
	output reg  [4:0] part_end
);

`include "spi_defs.vh"

	// ------------------------------------------------------------------
	// Scatter modes
	// ------------------------------------------------------------------
	localparam [4:0] M_LINEAR  = 5'd0;   // dest = base + i
	localparam [4:0] M_32_B0   = 5'd1;   // dest = base + i*4 + 0
	localparam [4:0] M_32_B1   = 5'd2;   // dest = base + i*4 + 1
	localparam [4:0] M_32_B2   = 5'd3;   // dest = base + i*4 + 2
	localparam [4:0] M_32_B3   = 5'd4;   // dest = base + i*4 + 3
	localparam [4:0] M_32_W01  = 5'd5;   // dest = base + (i>>1)*4 + 0 + (i&1)
	localparam [4:0] M_32_W23  = 5'd6;   // dest = base + (i>>1)*4 + 2 + (i&1)
	localparam [4:0] M_24_B0   = 5'd7;   // dest = base + i*3 + 0
	localparam [4:0] M_24_B1   = 5'd8;   // dest = base + i*3 + 1
	localparam [4:0] M_24_B2   = 5'd9;   // dest = base + i*3 + 2
	localparam [4:0] M_24_W01  = 5'd10;  // dest = base + (i>>1)*3 + (1 - (i&1))
	// LINEAR, plus MAME's sprite_reorder() rotated into the destination: within
	// each 64-byte group the 32 words are permuted so that output word 2j comes
	// from input word j and output word 2j+1 from input word j+16. As an index
	// that is one rotate -- dest = {i[5:0] rotated left by one word}.
	//
	// This is a LOAD-time permutation in a project whose rule is that graphics
	// decryption happens at FETCH time (PLAN.md 5), and deliberately so.
	// sprite_reorder is not decryption, it is an address swizzle, and doing it
	// here is free: the loader computes a destination per byte regardless.
	// Doing it at fetch time is not free -- it puts the two halves of a 16-pixel
	// row 32 bytes apart instead of 2, so a row would cost six SDRAM reads
	// instead of three, doubling sprite bandwidth on the one set that already
	// has the most sprite data.
	// SPRITE INTERLEAVE. The three plane-pair chunks used to sit megabytes
	// apart, so a 16-pixel row -- two 16-bit words from each -- cost THREE
	// SDRAM round trips. Interleaved, a row's twelve bytes are contiguous:
	//
	//   dest = base + tile*192 + row*12 + half*6 + byte
	//
	// and twelve bytes from a 4- or 8-aligned start never span more than two
	// 8-byte reads, so a row costs TWO. That is a third off the sprite engine's
	// bus demand, which is what it starves on (PLAN.md, sprite starvation).
	//
	// Which chunk a part carries is folded into its BASE, as +0, +2 or +4 --
	// the three chunks' words alternate inside each 6-byte half -- so no extra
	// table field is needed.
	//
	// M_SPR_ILV_R is the same with MAME's sprite_reorder() applied to the
	// source index first, for the RISE10 sets. The two permutations compose:
	// reorder moves words inside a 64-byte group, which is one tile, so it
	// changes row and half but never the tile.
	localparam [4:0] M_SPR_ILV   = 5'd11;
	localparam [4:0] M_SPR_ILV_R = 5'd12;

	// Part indices are 4 bits, and part_end (which spi_jtag_peek reports by bit
	// position) is 4 bits with it. That is the reason rdft2's six sprite ROMs
	// are ONE loader part rather than six: at a 6 MB chunk stride they are
	// contiguous from SDR_SPRITES_BASE, so one LINEAR run places all of them,
	// and 19 parts would not have fit. check_mra.py still checks all six
	// individually, by walking that part's MRA members.
	localparam [4:0] NPARTS_RDFTS = 5'd14;
	localparam [4:0] NPARTS_RDFT  = 5'd15;
	localparam [4:0] NPARTS_RDFT2 = 5'd17;
	localparam [4:0] NPARTS_RFJET = 5'd17;
	// Authentic flash. rdft gains two parts, because its one assembled image
	// becomes two source ROMs plus a blank; rdft2 and rfjet keep seventeen,
	// because their image was already two parts and the second sound ROM they
	// carry for the Z80 program is one of the sources.
	// viprp1: fifteen parts, and AUTHENTIC ONLY. Its flash payload is two
	// COMPRESSED jobs and the second reads the 386's own interleaved program
	// image rather than a ROM file (tools/build_soundflash.py: "the only game
	// whose second job reads the PROGRAM ROM"), so no MRA can assemble a
	// pre-flashed image out of file slices the way rdft2's does. The game
	// reading it itself is the whole point of the authentic path.
	localparam [4:0] NPARTS_VIPRP1 = 5'd15;
	localparam [4:0] NPARTS_RDFT_U  = 5'd17;
	localparam [4:0] NPARTS_RDFT2_U = 5'd17;
	localparam [4:0] NPARTS_RFJET_U = 5'd17;

	reg [4:0] nparts;
	always @* case (set_id)
		SET_RDFT : nparts = set_upd ? NPARTS_RDFT_U  : NPARTS_RDFT;
		SET_RDFT2: nparts = set_upd ? NPARTS_RDFT2_U : NPARTS_RDFT2;
		SET_RFJET: nparts = set_upd ? NPARTS_RFJET_U : NPARTS_RFJET;
		SET_VIPRP1: nparts = NPARTS_VIPRP1;
		default  : nparts = NPARTS_RDFTS;
	endcase

	// ------------------------------------------------------------------
	// Part tables. The order in each must match the <part> order in the MRA,
	// and tools/check_mra.py checks exactly that against MAME's driver --
	// nothing at runtime can, because the MRA carries no scatter information.
	// A case statement rather than a parameter array: Quartus 17.0 handles
	// unpacked-array parameters unevenly.
	//
	// SXX2C differs more than it looks. Its 386 program is four byte-lanes
	// instead of two bytes plus a word, its text layer is three byte-lanes
	// instead of a word plus a byte, and it has NO Z80 part at all -- that
	// region is RAM the 386 fills through port 0x688 before releasing the Z80
	// from reset. The sample part is the pre-programmed flash image the MRA
	// assembles from the cartridge's own sound ROMs, and `sound01` is absent
	// for rdft: measured, the 386 never reads that window once the flash is
	// programmed (section 0). rdft2 is the exception -- it keeps its Z80
	// program there, so its table carries one 128 KB slice of it.
	// ------------------------------------------------------------------
	reg [4:0]  part;
	reg [25:0] in_off;     // bytes of this part taken from ioctl
	reg [25:0] out_off;    // bytes of this part emitted into SDRAM

	// The table's outputs are REGISTERED, and the table is read one part ahead
	// so the registered copy is valid the same cycle `part` changes.
	//
	// Combinationally, the mux fed the adder that produces sdr_addr, which put
	// a 17-way 26-bit select in the address path: clk_ram missed setup by
	// 0.005 ns on part[1] -> sdr_addr[24] the moment `part` widened to 5 bits.
	// Registering costs nothing here -- a part boundary is followed by the
	// decoder's start pulse and at least one feed before anything can be
	// emitted -- and it cuts the path in two, mux into a flop and flop into
	// the adder.
	reg [25:0] part_base,   part_size;
	reg [4:0]  part_mode;
	reg [25:0] part_base_r, part_size_r;
	reg [4:0]  part_mode_r;

	wire       part_done;
	wire       last_part;
	// Held at 0 during reset on purpose. `part_size_r` is not yet loaded there,
	// so `part_in_full` reads true against a zero size and part_done fires
	// spuriously -- harmless for `part`, which reset holds at 0, but it would
	// otherwise leave the registered table pointing at part 1 on release.
	wire [4:0] part_sel = reset                     ? 5'd0
	                    : (part_done && !last_part) ? part + 5'd1
	                                                : part;

	always @(posedge clk) begin
		part_base_r <= part_base;
		part_size_r <= part_size;
		part_mode_r <= part_mode;
	end

	always @* begin
		case (set_id)

		// ---- TABLE rdft: SPI cartridge, pre-flashed (SXX2C) ----
		SET_RDFT: case (part_sel)
			//                                          base   size          mode
			5'd0 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B0;  end // raiden-fi_prg0_121196.u0211
			5'd1 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B1;  end // raiden-fi_prg1_121196.u0212
			5'd2 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B2;  end // raiden-fi_prg2_121196.u0210
			5'd3 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B3;  end // raiden-fi_prg3_121196.u029
			5'd4 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B0;  end // seibu_5.u0423
			5'd5 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B1;  end // seibu_6.u0424
			5'd6 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B2;  end // seibu_7.u048
			5'd7 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg1-d.u0415
			5'd8 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg1-p.u0410
			5'd9 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg2-d.u0424
			5'd10: begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg2-p.u049
			5'd11: begin part_base = SDR_SPRITES_BASE + 26'd0;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-1.u0322
			5'd12: begin part_base = SDR_SPRITES_BASE + 26'd2;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-2.u0324
			5'd13: begin part_base = SDR_SPRITES_BASE + 26'd4;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-3.u0323
			// The authentic tail is in MAME's OWN region order -- sound01's
			// two ROMs, then soundflash1's blank -- because that is the order
			// an MRA has to send them in for check_mra.py to hold each one
			// against the ROM_START entry it claims to be. That check compares
			// the comment to MAME's ROM name exactly, so these say the name and
			// nothing else: 14 and 15 are the updater's two sources, 16 is the
			// blank it programs. 15 and 16 are unreachable pre-flashed --
			// nparts stops the walk at 15.
			5'd14: if (set_upd)
			       begin part_base = SDR_PCMSRC_BASE;                    part_size = 26'h020_0000; part_mode = M_LINEAR; end // gun_dogs_pcm.u0217
			  else begin part_base = SDR_PCM_BASE;                       part_size = 26'h020_0000; part_mode = M_LINEAR; end // pre-programmed flash image
			5'd15: begin part_base = SDR_SND01_BASE;                     part_size = 26'h008_0000; part_mode = M_LINEAR; end // seibu_8.u0216
			default:begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // flash0_blank_region80.u1053 + 1 MB of FF
		endcase

		// ---- TABLE rdft2: SPI cartridge, decoded sample flash (SXX2C) ----
		//
		// Differences from rdft, all read off MAME's ROM_START(rdft2):
		//   * twice the tiles (12 MB), so the second bg group sits at +6 MB
		//   * text lanes come in the order fix0(1), fix1(0), fixp(2)
		//   * 18 MB of sprites as three 6 MB plane-pair chunks, one loader part
		//     each -- obj3 first, then obj2, then obj1, which is MAME's order
		//     and not the numeric one. M_SPR_ILV_R, not M_SPR_ILV: RISE10 sets
		//     carry sprite_reorder() as well as the interleave
		//   * the sample flash is two parts: the region stamp plus a verbatim
		//     slice of pcm.u0217, then sound1.u0222 COMPRESSED. The MRA marks
		//     that last part CODEC_BPE_DPCM, so its size here is the
		//     compressed length -- 0x4C665 in, 0x730ED out (PLAN.md 0)
		//   * a 17th part that neither rdft nor rdfts has: sound1.u0222 AGAIN,
		//     this time whole, because it also holds rdft2's Z80 program. The
		//     386 reads that through the sound01 window before releasing the
		//     Z80, so unlike rdft's (whose copy is already in maincpu) it has to
		//     be in SDRAM for spi_cpu to answer that window at all. Stored
		//     PACKED, one byte per 386 dword; the window's other three byte
		//     lanes are zero in MAME's region too. The whole ROM rather than
		//     just the program at 0x60000: see SDR_SND01_BASE in spi_defs.vh.
		SET_RDFT2: case (part_sel)
		//                                                    base   size          mode
		5'd0 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B0;  end // prg0.tun
		5'd1 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B1;  end // prg1.bin
		5'd2 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B2;  end // prg2.bin
		5'd3 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B3;  end // prg3.bin
		5'd4 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B1;  end // fix0.u0524
		5'd5 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B0;  end // fix1.u0518
		5'd6 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B2;  end // fixp.u0514
		5'd7 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h040_0000; part_mode = M_24_W01; end // bg-1d.u0535
		5'd8 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h020_0000; part_mode = M_24_B2;  end // bg-1p.u0537
		5'd9 : begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h040_0000; part_mode = M_24_W01; end // bg-2d.u0536
		5'd10: begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h020_0000; part_mode = M_24_B2;  end // bg-2p.u0538
		5'd11: begin part_base = SDR_SPRITES_BASE + 26'd0;          part_size = 26'h060_0000; part_mode = M_SPR_ILV_R; end // sprites chunk 0: obj3.u0434 + obj3b.u0433
		5'd12: begin part_base = SDR_SPRITES_BASE + 26'd2;          part_size = 26'h060_0000; part_mode = M_SPR_ILV_R; end // sprites chunk 1: obj2.u0431 + obj2b.u0432
		5'd13: begin part_base = SDR_SPRITES_BASE + 26'd4;          part_size = 26'h060_0000; part_mode = M_SPR_ILV_R; end // sprites chunk 2: obj1.u0429 + obj1b.u0430
		// Authentic: the two sound01 ROMs and then a blank flash, in MAME's own
		// region order, in place of the two slices of a derived image. Part 15
		// is the SAME ROM either way and lands in the same place -- pre-flashed
		// it is there for the Z80 program, authentic it is also the updater's
		// second source -- so only its position in the list moves.
		5'd14: if (set_upd)
		       begin part_base = SDR_PCMSRC_BASE;                   part_size = 26'h020_0000; part_mode = M_LINEAR; end // pcm.u0217
		  else begin part_base = SDR_PCM_BASE;                      part_size = 26'h017_C247; part_mode = M_LINEAR; end // flash head: region stamp + pcm.u0217
		5'd15: if (set_upd)
		       begin part_base = SDR_SND01_BASE;                    part_size = 26'h008_0000; part_mode = M_LINEAR; end // sound1.u0222
		  else begin part_base = SDR_PCM_BASE + 26'h017_C247;       part_size = 26'h004_C665; part_mode = M_LINEAR; end // flash tail: sound1.u0222 compressed
		default: if (set_upd)
		       begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // flash0_blank_region80.u1053 + 1 MB of FF
		  else begin part_base = SDR_SND01_BASE;                    part_size = 26'h008_0000; part_mode = M_LINEAR; end // sound1.u0222 whole: holds the Z80 program at 0x60000
		endcase

		// ---- TABLE rfjet: SPI cartridge, decoded sample flash (SXX2C) ----
		//
		// The same shape as rdft2 -- same board, same updater generation, same
		// three text lanes in the same order -- with four differences, all read
		// off MAME's ROM_START(rfjet):
		//   * 9 MB of tiles, not 12. The second bg group still sits at +6 MB
		//     (bg-2d loads at region 0x600000), but both of its ROMs are half
		//     rdft2's size. 9 MB is still over the 6 MB threshold, so the fore
		//     layer base is 0x8000 the same as rdft2's -- spi_top.sv.
		//   * 24 MB of sprites as three 8 MB chunks, and here MAME's file order
		//     IS the numeric one: obj-1 at region 0, obj-2 at 8 MB, obj-3 at 16.
		//     rdft2's is obj3, obj2, obj1, which is exactly the sort of thing
		//     that gets carried across by mistake. M_SPR_ILV_R again: RISE11
		//     carries sprite_reorder like RISE10 does.
		//   * a different flash payload -- 0x189DD5 copied from pcm-d.u0227,
		//     then 0x41C08 compressed bytes of sound1.u0222 expanding to
		//     0x5F6F5. Both lengths come out of tools/build_soundflash.py,
		//     which reports source bytes consumed as well as bytes produced;
		//     the decoded one cannot be read off the job record, whose `len`
		//     field is the OUTPUT length.
		//   * the Z80 program is at sound1.u0222[0x44000], not [0x60000] -- but
		//     part 16 carries the ROM whole for both sets, so nothing here
		//     depends on that and rfjet's unmeasured program LENGTH does not
		//     matter either. See SDR_SND01_BASE in spi_defs.vh.
		SET_RFJET: case (part_sel)
		//                                                    base   size          mode
		5'd0 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B0;  end // prg0.u0211
		5'd1 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B1;  end // prg1.u0212
		5'd2 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B2;  end // prg2.u0221
		5'd3 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B3;  end // prg3.u0220
		5'd4 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B1;  end // fix0.u0524
		5'd5 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B0;  end // fix1.u0518
		5'd6 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B2;  end // fixp.u0514
		5'd7 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h040_0000; part_mode = M_24_W01; end // bg-1d.u0543
		5'd8 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h020_0000; part_mode = M_24_B2;  end // bg-1p.u0544
		5'd9 : begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h020_0000; part_mode = M_24_W01; end // bg-2d.u0545
		5'd10: begin part_base = SDR_TILES_BASE + 26'h060_0000;     part_size = 26'h010_0000; part_mode = M_24_B2;  end // bg-2p.u0546
		5'd11: begin part_base = SDR_SPRITES_BASE + 26'd0;          part_size = 26'h080_0000; part_mode = M_SPR_ILV_R; end // obj-1.u0442
		5'd12: begin part_base = SDR_SPRITES_BASE + 26'd2;          part_size = 26'h080_0000; part_mode = M_SPR_ILV_R; end // obj-2.u0443
		5'd13: begin part_base = SDR_SPRITES_BASE + 26'd4;          part_size = 26'h080_0000; part_mode = M_SPR_ILV_R; end // obj-3.u0444
		// Authentic: as rdft2's, and here the two tails really are identical --
		// a PCM source ROM is 2 MB, a second sound ROM 512 KB and a blank flash
		// 2 MB on every cartridge set. It is only the DERIVED images that
		// differ per game, which is the argument for this path in one line.
		5'd14: if (set_upd)
		       begin part_base = SDR_PCMSRC_BASE;                   part_size = 26'h020_0000; part_mode = M_LINEAR; end // pcm-d.u0227
		  else begin part_base = SDR_PCM_BASE;                      part_size = 26'h018_9DD5; part_mode = M_LINEAR; end // flash head: region stamp + pcm-d.u0227
		5'd15: if (set_upd)
		       begin part_base = SDR_SND01_BASE;                    part_size = 26'h008_0000; part_mode = M_LINEAR; end // sound1.u0222
		  else begin part_base = SDR_PCM_BASE + 26'h018_9DD5;       part_size = 26'h004_1C08; part_mode = M_LINEAR; end // flash tail: sound1.u0222 compressed
		default: if (set_upd)
		       begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // flash0_blank_region80.u1053 + 1 MB of FF
		  else begin part_base = SDR_SND01_BASE;                    part_size = 26'h008_0000; part_mode = M_LINEAR; end // sound1.u0222 whole: holds the Z80 program at 0x44000
		endcase

		// ---- TABLE viprp1: SPI cartridge, authentic flash only (SXX2C) ----
		//
		// Same decryption as rdft -- MAME's init_viprp1 is init_sei252, so the
		// text, tile and sprite keys and the 4 MB sprite chunk are the ones
		// already wired for the SEI252 sets. What differs from rdft:
		//   * text is a WORD plus a byte, as rdfts has it, not three byte lanes
		//   * 6 MB of tiles, but the second bg group is HALF rdft's (0x100000 +
		//     0x80000 against 0x200000 + 0x100000) at the same 3 MB base
		//   * the PCM source is 1 MB on ONE byte lane -- generation A -- where
		//     rdft's is 2 MB on two. spi_cpu.sv's pcmsrc_1lane is that bit.
		//   * NO second sound ROM at all, so there is no snd01 part: viprp1's
		//     compressed tail lives in the 386 program image, which the game
		//     reads through a window that is already mapped.
		SET_VIPRP1: case (part_sel)
		//                                                    base   size          mode
		5'd0 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B0;  end // seibu1.211
		5'd1 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B1;  end // seibu2.212
		5'd2 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B2;  end // seibu3.210
		5'd3 : begin part_base = SDR_PRG_BASE;                      part_size = 26'h008_0000; part_mode = M_32_B3;  end // seibu4.29
		5'd4 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h002_0000; part_mode = M_24_W01; end // seibu5.u0413
		5'd5 : begin part_base = SDR_CHARS_BASE;                    part_size = 26'h001_0000; part_mode = M_24_B2;  end // seibu6.u048
		5'd6 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h020_0000; part_mode = M_24_W01; end // v_bg-11.415
		5'd7 : begin part_base = SDR_TILES_BASE;                    part_size = 26'h010_0000; part_mode = M_24_B2;  end // v_bg-12.415
		5'd8 : begin part_base = SDR_TILES_BASE + 26'h030_0000;     part_size = 26'h010_0000; part_mode = M_24_W01; end // v_bg-21.410
		5'd9 : begin part_base = SDR_TILES_BASE + 26'h030_0000;     part_size = 26'h008_0000; part_mode = M_24_B2;  end // v_bg-22.416
		5'd10: begin part_base = SDR_SPRITES_BASE + 26'd0;          part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // v_obj-1.322
		5'd11: begin part_base = SDR_SPRITES_BASE + 26'd2;          part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // v_obj-2.324
		5'd12: begin part_base = SDR_SPRITES_BASE + 26'd4;          part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // v_obj-3.323
		5'd13: begin part_base = SDR_PCMSRC_BASE;                   part_size = 26'h010_0000; part_mode = M_LINEAR; end // v_pcm.215
		default:begin part_base = SDR_PCM_BASE;                     part_size = 26'h020_0000; part_mode = M_LINEAR; end // flash0_blank_regionbe.u1053 + 1 MB of FF
		endcase

		// ---- TABLE rdfts: SXX2E single board ----
		default: case (part_sel)
			//                                          base   size          mode
			5'd0 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B0;  end // seibu_1.u0259
			5'd1 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h008_0000; part_mode = M_32_B1;  end // raiden-f_prg2.u0258
			5'd2 : begin part_base = SDR_PRG_BASE;                       part_size = 26'h010_0000; part_mode = M_32_W23; end // raiden-f_prg34.u0262
			5'd3 : begin part_base = SDR_Z80_BASE;                       part_size = 26'h002_0000; part_mode = M_LINEAR; end // seibu_zprg.u1139
			5'd4 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h002_0000; part_mode = M_24_W01; end // raiden-f_fix.u0535
			5'd5 : begin part_base = SDR_CHARS_BASE;                     part_size = 26'h001_0000; part_mode = M_24_B2;  end // seibu_fix2.u0528
			5'd6 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg1-d.u0526
			5'd7 : begin part_base = SDR_TILES_BASE;                     part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg1-p.u0531
			5'd8 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h020_0000; part_mode = M_24_W01; end // gun_dogs_bg2-d.u0534
			5'd9 : begin part_base = SDR_TILES_BASE + 26'h030_0000;      part_size = 26'h010_0000; part_mode = M_24_B2;  end // gun_dogs_bg2-p.u0530
			5'd10: begin part_base = SDR_SPRITES_BASE + 26'd0;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-1.u0322
			5'd11: begin part_base = SDR_SPRITES_BASE + 26'd2;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-2.u0324
			5'd12: begin part_base = SDR_SPRITES_BASE + 26'd4;           part_size = 26'h040_0000; part_mode = M_SPR_ILV; end // gun_dogs_obj-3.u0323
			default:begin part_base = SDR_PCM_BASE;                      part_size = 26'h020_0000; part_mode = M_LINEAR; end // raiden-f_pcm2.u0975
		endcase

		endcase
	end

	assign last_part = (part == nparts - 5'd1);

	// Destination offset within the part, per scatter mode. This indexes
	// EMITTED bytes: for a decoded part the source offset is not the
	// destination offset, and it is the output that has to land in order.
	wire [25:0] off   = out_off;
	wire [25:0] off_h = {1'b0, out_off[25:1]};   // off >> 1

	// Sprite interleave. `sri` is the source index with sprite_reorder applied
	// (a rotate inside each 64-byte group); `siv` picks it or the raw index.
	// tile*192 is tile*128 + tile*64 and row*12 is row*8 + row*4, so the whole
	// thing is shifts and adds.
	wire [25:0] sri  = {off[25:6], off[4:1], off[5], off[0]};
	wire [25:0] siv  = (part_mode_r == M_SPR_ILV_R) ? sri : off;
	wire [25:0] ilv  = {siv[24:6], 7'd0} + {siv[25:6], 6'd0}
	                 + {19'd0, siv[5:2], 3'd0} + {20'd0, siv[5:2], 2'd0}
	                 + (siv[1] ? 26'd6 : 26'd0) + {25'd0, siv[0]};

	reg [25:0] scat;
	always @* begin
		// Every term is written out at the full 26 bits. These used to be sized
		// by hand for a 25-bit address and each one needed a different patch
		// when the map grew; `off_h` exists so the halved forms cannot drift
		// from each other again.
		case (part_mode_r)
			M_LINEAR: scat =  off;
			M_32_B0 : scat = {off[23:0], 2'b00};
			M_32_B1 : scat = {off[23:0], 2'b00} + 26'd1;
			M_32_B2 : scat = {off[23:0], 2'b00} + 26'd2;
			M_32_B3 : scat = {off[23:0], 2'b00} + 26'd3;
			M_32_W01: scat = {off_h[23:0], 2'b00}         + {25'd0, off[0]};
			M_32_W23: scat = {off_h[23:0], 2'b00} + 26'd2 + {25'd0, off[0]};
			M_24_B0 : scat = {off[24:0], 1'b0} + off;
			M_24_B1 : scat = {off[24:0], 1'b0} + off + 26'd1;
			M_24_B2 : scat = {off[24:0], 1'b0} + off + 26'd2;
			M_24_W01: scat = {off_h[24:0], 1'b0} + off_h + {25'd0, ~off[0]};
			M_SPR_ILV, M_SPR_ILV_R: scat = ilv;
			default : scat =  off;
		endcase
	end

	// REGISTERED, and `sdr_addr` is loaded from it rather than from the sum.
	// The scatter is a 13-way mux over 26-bit shift-adds and then a 26-bit add
	// against the base, and at 80% ALMs the fitter cannot reliably place all
	// of that inside one clk_ram period -- every failing endpoint in the fit
	// before this was out_off[N] -> sdr_addr[N].
	//
	// Registering is free because `out_off` only moves on `emit`, and two
	// emits are always at least two cycles apart: the second waits for the
	// first's write to retire, and `busy` is still set in the cycle the ack
	// arrives. A part boundary is the same story -- out_off clears and
	// part_base_r loads together, and the decoder cannot produce the new
	// part's first byte until two cycles later.
	wire [25:0] dest = part_base_r + scat;
	reg  [25:0] dest_r;
	always @(posedge clk) dest_r <= dest;

	// ------------------------------------------------------------------
	// Decoder
	// ------------------------------------------------------------------
	// One byte of skid between ioctl and the decoder. The previous loader
	// consumed ioctl_wr in the cycle it arrived and silently DROPPED the byte
	// if a write was in flight; ioctl_wait has a cycle of latency, so that only
	// ever worked because the HPS is slower than the SDRAM. A decoded part
	// stalls for hundreds of cycles, so hold the byte instead of losing it.
	reg       hold_valid;
	reg [7:0] hold_data;

	wire       dec_in_ready, dec_out_valid, dec_idle;
	wire [7:0] dec_out_data;

	reg  busy;
	reg  part_step;      // one cycle at each part boundary, arms the decoder
	reg  dl_d;

	wire download = ioctl_download && (ioctl_index == 8'd0);

	// ioctl_wr is a ONE-clk_sys-cycle pulse and this module runs on clk_ram,
	// which is exactly 2x clk_sys and phase aligned from the same VCO -- so the
	// pulse is high across TWO of our clock edges and the level cannot be used
	// as "a byte arrived". Acting on it twice counted every byte twice and, when
	// `feed` fell between the two edges, re-armed hold_valid on a byte that had
	// already been consumed and emitted it a second time, to the next
	// destination. That is a stretched, wrong ROM image, and it is what a MiSTer
	// was measurably doing: bytes_in = 46,792,704, exactly twice rdfts' image,
	// with all four region checksums failing (PLAN.md 10c).
	//
	// Nothing simulated it because the testbench drove one-cycle pulses.
	// tb_rom_loader now runs every set both ways.
	reg  ioctl_wr_d;
	wire ioctl_wr_rise = ioctl_wr && !ioctl_wr_d;

	// The part's input is spent. What ends a part is bytes IN, not bytes out:
	// a decoded part's output length is a property of the data, not the table.
	wire part_in_full = (in_off == part_size_r);
	wire feed         = hold_valid && !part_in_full && dec_in_ready;
	wire emit         = dec_out_valid && !busy;
	assign part_done  = part_in_full && dec_idle && !busy;

	wire [3:0] codec = part_codec[{part, 2'b00} +: 4];

	spi_rom_decode decode
	(
		.clk       (clk),
		.reset     (reset),
		.codec     (codec),
		.start     ((download && !dl_d) || part_step),
		.in_valid  (hold_valid && !part_in_full),
		.in_data   (hold_data),
		.in_ready  (dec_in_ready),
		.out_valid (dec_out_valid),
		.out_data  (dec_out_data),
		.out_ready (emit),
		.idle      (dec_idle)
	);

	// ------------------------------------------------------------------
	// Write sequencing
	// ------------------------------------------------------------------
	reg seen_download;   // rom_ready must not assert before the first download

	always @(posedge clk) begin
		if (reset) begin
			part          <= 5'd0;
			in_off        <= 26'd0;
			out_off       <= 26'd0;
			busy          <= 1'b0;
			ioctl_wait    <= 1'b0;
			sdr_req       <= 1'b0;
			sdr_rnw       <= 1'b1;
			rom_ready     <= 1'b0;
			seen_download <= 1'b0;
			hold_valid    <= 1'b0;
			part_step     <= 1'b0;
			dl_d          <= 1'b0;
			ioctl_wr_d    <= 1'b0;
			bytes_in      <= 26'd0;
			bytes_out     <= 26'd0;
			part_end      <= 5'd0;
		end
		else begin
			part_step  <= 1'b0;
			dl_d       <= download;
			ioctl_wr_d <= ioctl_wr;

			// A write retires when ack catches up with req.
			if (busy && (sdr_ack == sdr_req)) busy <= 1'b0;

			// Emitting is deliberately outside the `download` arm: a decoded
			// part is still draining after the HPS drops ioctl_download, and
			// those bytes are as real as the rest.
			if (emit) begin
				sdr_addr  <= {dest_r[25:1], 1'b0};
				sdr_din   <= {dec_out_data, dec_out_data};
				sdr_be    <= dest_r[0] ? 2'b10 : 2'b01;
				sdr_rnw   <= 1'b0;
				sdr_req   <= ~sdr_req;
				busy      <= 1'b1;
				out_off   <= out_off + 26'd1;
				bytes_out <= bytes_out + 26'd1;
			end

			if (feed) begin
				hold_valid <= 1'b0;
				ioctl_wait <= 1'b0;
				in_off     <= in_off + 26'd1;
			end

			if (part_done) begin
				in_off    <= 26'd0;
				out_off   <= 26'd0;
				part_step <= 1'b1;
				if (!last_part) part <= part + 5'd1;
			end

			if (download) begin
				seen_download <= 1'b1;
				rom_ready     <= 1'b0;
				part_end      <= part;

				// Capture last so a byte arriving in the same cycle the held
				// one is consumed replaces it rather than being dropped.
				if (ioctl_wr_rise) begin
					bytes_in   <= bytes_in + 26'd1;
					hold_data  <= ioctl_dout;
					hold_valid <= 1'b1;
					ioctl_wait <= 1'b1;
				end
			end
			else begin
				// Image is in place once the decoder has drained and the last
				// write has retired.
				if (!busy && dec_idle && !hold_valid) begin
					if (seen_download) rom_ready <= 1'b1;
					part    <= 5'd0;
					in_off  <= 26'd0;
					out_off <= 26'd0;
				end
			end
		end
	end

endmodule
