//==========================================================================
//  SlopperPI - RISE11 sprite decryption constants
//
//  GENERATED by tools/gen_rise11_tables.py from
//  src/mame/seibu/seibuspi_m.cpp
//  Do not edit.
//
//  The two gathers below are checked at generation time to consume all 48
//  source bits of b1/b2/b3 exactly once, which is the property a mistyped
//  entry cannot have.
//
//  Only rfjet's keys are emitted. feversoc shares the codec but not the
//  hardware -- it is an SH-2 board in a different driver -- and it also
//  takes an extra +1 partial sum this core has no reason to carry. Its
//  keys, for the record: 9DF5B2 9AE999 4A32E9 968BD5 1D97AC.
//==========================================================================

// plane543 = partial_carry_sum(gather543, R11_ADD543, R11_MASK543)
//            ^ R11_XOR543
localparam [23:0] R11_ADD543  = 24'hABCB64;
localparam [23:0] R11_MASK543 = 24'h55AADD;
localparam [23:0] R11_XOR543  = 24'hAB6A4C;

// plane210's addend is the WORD INDEX, not a constant -- this is the whole
// difference between RISE11 and RISE10 as far as the core is concerned.
localparam [23:0] R11_MASK210 = 24'hD6375B;
localparam [23:0] R11_XOR210  = 24'h8BF23B;

// Destination bit d of each gather takes bit [n] of the named input word.
// The arguments must be simple identifiers: Verilog cannot index a
// parenthesised expression, so no (v) here.
`define R11_GATHER543(b1, b2, b3) { \
	b2[ 0], b3[ 2], b1[ 4], b2[13], \
	b3[ 9], b1[15], b2[ 7], b1[ 3], \
	b3[ 5], b2[10], b2[ 2], b3[ 1], \
	b1[ 9], b2[ 5], b1[ 2], b1[12], \
	b1[11], b3[ 4], b3[14], b2[12], \
	b3[ 3], b3[12], b1[ 6], b2[11] }

`define R11_GATHER210(b1, b2, b3) { \
	b3[15], b1[ 5], b2[ 3], b2[15], \
	b1[10], b3[ 6], b3[10], b1[ 8], \
	b3[13], b2[ 8], b3[11], b1[ 0], \
	b2[ 6], b3[ 7], b2[ 1], b3[ 8], \
	b2[ 9], b2[ 4], b2[14], b1[ 7], \
	b3[ 0], b1[13], b1[ 1], b1[14] }
