//==========================================================================
//  SlopperPI - RISE10 sprite decryption constants
//
//  GENERATED by tools/gen_rise10_tables.py from
//  src/mame/seibu/seibuspi_m.cpp
//  Do not edit.
//
//  Unlike SEI252 there is no key table and no address term: every operand
//  below is a constant, which is why this unit needs no per-tile fetch.
//==========================================================================

localparam [15:0] R10_ADD54    = 16'hABCB;
localparam [15:0] R10_MASK54   = 16'h55AA;
localparam [15:0] R10_XOR54    = 16'h6699;
localparam [31:0] R10_ADD3210  = 32'h6543219B;
localparam [31:0] R10_MASK3210 = 32'h1D463748;
localparam [31:0] R10_XOR3210  = 32'h0CA352A9;

// bitswap<32>: destination bit d takes source bit R10_BS[d].
// MAME lists the sources starting at destination 31, so the list is
// reversed here and indexed by destination.
// The argument must be a simple identifier: Verilog cannot index a
// parenthesised expression, so no (v) here.
`define R10_BITSWAP(v) { \
	v[23], v[13], v[24], v[ 4], \
	v[16], v[12], v[25], v[30], \
	v[ 3], v[ 5], v[29], v[17], \
	v[14], v[22], v[ 2], v[11], \
	v[27], v[ 6], v[15], v[21], \
	v[ 1], v[28], v[10], v[20], \
	v[ 7], v[31], v[26], v[ 0], \
	v[18], v[ 9], v[19], v[ 8] }
