//==========================================================================
//  SlopperPI - SEI252 sprite decryption tables
//
//  GENERATED by tools/gen_spi_tables.py -- do not edit.
//  Source: ~/proj/mame/src/mame/seibu/seibuspi_m.cpp
//==========================================================================

	// key_table[256], indexed by addr[7:0].
	reg [15:0] key_table [0:255];
	initial begin
		key_table[  0] = 16'h3AD7;  key_table[  1] = 16'h54B1;  key_table[  2] = 16'h2D41;  key_table[  3] = 16'h8CA0;
		key_table[  4] = 16'hA69B;  key_table[  5] = 16'h9018;  key_table[  6] = 16'h9DB9;  key_table[  7] = 16'h6559;
		key_table[  8] = 16'hE9A7;  key_table[  9] = 16'hB087;  key_table[ 10] = 16'h8A5E;  key_table[ 11] = 16'h821C;
		key_table[ 12] = 16'hAAFC;  key_table[ 13] = 16'h2AE7;  key_table[ 14] = 16'h557B;  key_table[ 15] = 16'hCD80;
		key_table[ 16] = 16'hCFEE;  key_table[ 17] = 16'h653E;  key_table[ 18] = 16'h9B31;  key_table[ 19] = 16'h7AB5;
		key_table[ 20] = 16'h8B2A;  key_table[ 21] = 16'hBDA8;  key_table[ 22] = 16'h707A;  key_table[ 23] = 16'h3C83;
		key_table[ 24] = 16'hCBB7;  key_table[ 25] = 16'h7157;  key_table[ 26] = 16'h8226;  key_table[ 27] = 16'h5C4A;
		key_table[ 28] = 16'h8BF2;  key_table[ 29] = 16'h6397;  key_table[ 30] = 16'h13E2;  key_table[ 31] = 16'h3102;
		key_table[ 32] = 16'h8093;  key_table[ 33] = 16'h44CD;  key_table[ 34] = 16'h5F2D;  key_table[ 35] = 16'h7639;
		key_table[ 36] = 16'hA7A4;  key_table[ 37] = 16'h9974;  key_table[ 38] = 16'h5263;  key_table[ 39] = 16'h8318;
		key_table[ 40] = 16'hB78C;  key_table[ 41] = 16'hA120;  key_table[ 42] = 16'hAFB4;  key_table[ 43] = 16'h615F;
		key_table[ 44] = 16'h6E0B;  key_table[ 45] = 16'h1D7D;  key_table[ 46] = 16'h8C29;  key_table[ 47] = 16'h4466;
		key_table[ 48] = 16'h3F35;  key_table[ 49] = 16'h794E;  key_table[ 50] = 16'hAEA6;  key_table[ 51] = 16'h601C;
		key_table[ 52] = 16'hE478;  key_table[ 53] = 16'hCF6E;  key_table[ 54] = 16'h4EE3;  key_table[ 55] = 16'hA009;
		key_table[ 56] = 16'h4B99;  key_table[ 57] = 16'h51D3;  key_table[ 58] = 16'h3474;  key_table[ 59] = 16'h3E4D;
		key_table[ 60] = 16'hE5B7;  key_table[ 61] = 16'h9088;  key_table[ 62] = 16'hB5C0;  key_table[ 63] = 16'hBA9F;
		key_table[ 64] = 16'h5646;  key_table[ 65] = 16'hA0AF;  key_table[ 66] = 16'h970B;  key_table[ 67] = 16'hB14F;
		key_table[ 68] = 16'h8216;  key_table[ 69] = 16'h2386;  key_table[ 70] = 16'h496D;  key_table[ 71] = 16'h9245;
		key_table[ 72] = 16'h7E4C;  key_table[ 73] = 16'hAD5F;  key_table[ 74] = 16'h89D9;  key_table[ 75] = 16'hB801;
		key_table[ 76] = 16'hDF64;  key_table[ 77] = 16'h8CA8;  key_table[ 78] = 16'hE019;  key_table[ 79] = 16'hDE9B;
		key_table[ 80] = 16'h6836;  key_table[ 81] = 16'h70E2;  key_table[ 82] = 16'h7DCD;  key_table[ 83] = 16'h7AC1;
		key_table[ 84] = 16'h98EF;  key_table[ 85] = 16'h71AA;  key_table[ 86] = 16'h7D6F;  key_table[ 87] = 16'h70BD;
		key_table[ 88] = 16'h9E14;  key_table[ 89] = 16'h75B6;  key_table[ 90] = 16'h8153;  key_table[ 91] = 16'hAB6C;
		key_table[ 92] = 16'h1F85;  key_table[ 93] = 16'h79CD;  key_table[ 94] = 16'hB2A1;  key_table[ 95] = 16'h934A;
		key_table[ 96] = 16'h6F74;  key_table[ 97] = 16'h37D7;  key_table[ 98] = 16'hA05A;  key_table[ 99] = 16'h6563;
		key_table[100] = 16'h1972;  key_table[101] = 16'h2DCD;  key_table[102] = 16'h7E59;  key_table[103] = 16'h6A60;
		key_table[104] = 16'h5163;  key_table[105] = 16'h84C4;  key_table[106] = 16'hC451;  key_table[107] = 16'h8D80;
		key_table[108] = 16'h4287;  key_table[109] = 16'h57E8;  key_table[110] = 16'hACC9;  key_table[111] = 16'h539D;
		key_table[112] = 16'hBE71;  key_table[113] = 16'hDB7C;  key_table[114] = 16'h9424;  key_table[115] = 16'hB224;
		key_table[116] = 16'hCC0F;  key_table[117] = 16'hE3DD;  key_table[118] = 16'hB79C;  key_table[119] = 16'h461E;
		key_table[120] = 16'h96A9;  key_table[121] = 16'h4C7C;  key_table[122] = 16'h5443;  key_table[123] = 16'h6B2B;
		key_table[124] = 16'h3CDC;  key_table[125] = 16'hBEE8;  key_table[126] = 16'h2602;  key_table[127] = 16'h3282;
		key_table[128] = 16'h7F9C;  key_table[129] = 16'h59C3;  key_table[130] = 16'hC69A;  key_table[131] = 16'h39F4;
		key_table[132] = 16'h5138;  key_table[133] = 16'hB7CA;  key_table[134] = 16'h6CA7;  key_table[135] = 16'h62E7;
		key_table[136] = 16'hC455;  key_table[137] = 16'h56CF;  key_table[138] = 16'h8A9A;  key_table[139] = 16'h695C;
		key_table[140] = 16'h5AF2;  key_table[141] = 16'hDEBF;  key_table[142] = 16'h4DBB;  key_table[143] = 16'hDAEC;
		key_table[144] = 16'hB564;  key_table[145] = 16'hC89C;  key_table[146] = 16'h7D2D;  key_table[147] = 16'h6DC3;
		key_table[148] = 16'hA15A;  key_table[149] = 16'h6584;  key_table[150] = 16'hB8EA;  key_table[151] = 16'hB7AC;
		key_table[152] = 16'h88D8;  key_table[153] = 16'hC5AA;  key_table[154] = 16'h98C5;  key_table[155] = 16'hC506;
		key_table[156] = 16'hC13C;  key_table[157] = 16'h7F59;  key_table[158] = 16'hAB65;  key_table[159] = 16'h8FC8;
		key_table[160] = 16'h3A3C;  key_table[161] = 16'hD5F6;  key_table[162] = 16'h554D;  key_table[163] = 16'h5682;
		key_table[164] = 16'h8CE7;  key_table[165] = 16'h40FC;  key_table[166] = 16'h8FD7;  key_table[167] = 16'h535C;
		key_table[168] = 16'h6AA0;  key_table[169] = 16'h52FE;  key_table[170] = 16'h8834;  key_table[171] = 16'h5316;
		key_table[172] = 16'h6C27;  key_table[173] = 16'h80A9;  key_table[174] = 16'h9E6F;  key_table[175] = 16'h2C08;
		key_table[176] = 16'h4092;  key_table[177] = 16'hC7C1;  key_table[178] = 16'hC468;  key_table[179] = 16'h9520;
		key_table[180] = 16'hBC4D;  key_table[181] = 16'hB621;  key_table[182] = 16'h3CDB;  key_table[183] = 16'hDCE8;
		key_table[184] = 16'h481F;  key_table[185] = 16'hD0BD;  key_table[186] = 16'h3A57;  key_table[187] = 16'h807E;
		key_table[188] = 16'h3025;  key_table[189] = 16'h5AA0;  key_table[190] = 16'h5E49;  key_table[191] = 16'hA29B;
		key_table[192] = 16'hD2D6;  key_table[193] = 16'h7BEE;  key_table[194] = 16'h97F0;  key_table[195] = 16'hE28E;
		key_table[196] = 16'h2FFF;  key_table[197] = 16'h48E4;  key_table[198] = 16'h6367;  key_table[199] = 16'h933F;
		key_table[200] = 16'h57C5;  key_table[201] = 16'h28D4;  key_table[202] = 16'h68A0;  key_table[203] = 16'hD22E;
		key_table[204] = 16'h39A6;  key_table[205] = 16'h9D2B;  key_table[206] = 16'h7A64;  key_table[207] = 16'h7E72;
		key_table[208] = 16'h5379;  key_table[209] = 16'hE86C;  key_table[210] = 16'h7554;  key_table[211] = 16'h8FBB;
		key_table[212] = 16'hC06A;  key_table[213] = 16'h9533;  key_table[214] = 16'h7EEC;  key_table[215] = 16'h4D52;
		key_table[216] = 16'hA800;  key_table[217] = 16'h5D35;  key_table[218] = 16'hA47D;  key_table[219] = 16'hE515;
		key_table[220] = 16'h8D19;  key_table[221] = 16'h703B;  key_table[222] = 16'h5A2E;  key_table[223] = 16'h627C;
		key_table[224] = 16'h7CEA;  key_table[225] = 16'h1B2C;  key_table[226] = 16'h5A05;  key_table[227] = 16'h8598;
		key_table[228] = 16'h9E00;  key_table[229] = 16'hCF01;  key_table[230] = 16'h62D9;  key_table[231] = 16'h7A10;
		key_table[232] = 16'h1F42;  key_table[233] = 16'h87CE;  key_table[234] = 16'h575D;  key_table[235] = 16'h6E23;
		key_table[236] = 16'h86EF;  key_table[237] = 16'h93C2;  key_table[238] = 16'h3D1A;  key_table[239] = 16'h89AA;
		key_table[240] = 16'hE199;  key_table[241] = 16'hBA1D;  key_table[242] = 16'h1B72;  key_table[243] = 16'h4513;
		key_table[244] = 16'h5131;  key_table[245] = 16'hC23C;  key_table[246] = 16'hBA9F;  key_table[247] = 16'hA069;
		key_table[248] = 16'hFBFB;  key_table[249] = 16'hDA92;  key_table[250] = 16'h42B2;  key_table[251] = 16'h3A48;
		key_table[252] = 16'hDB96;  key_table[253] = 16'h5FAD;  key_table[254] = 16'hBA96;  key_table[255] = 16'hC6EB;
	end

	// y3 permutation, selected by key_table[addr[7:0]][3:0].
	// MAME bitswap<16>(y3, bs[0]..bs[15]) => result[j] = y3[bs[15-j]].
	reg [15:0] y3p;
	always @* begin
		case (bsidx)
			4'd0 : y3p = {y3[15], y3[14], y3[13], y3[12], y3[11], y3[10], y3[9], y3[8], y3[7], y3[6], y3[5], y3[4], y3[3], y3[2], y3[1], y3[0]};
			4'd1 : y3p = {y3[7], y3[6], y3[5], y3[14], y3[0], y3[15], y3[4], y3[3], y3[2], y3[8], y3[9], y3[10], y3[11], y3[12], y3[13], y3[1]};
			4'd2 : y3p = {y3[9], y3[15], y3[14], y3[13], y3[12], y3[0], y3[1], y3[2], y3[10], y3[8], y3[7], y3[6], y3[5], y3[4], y3[3], y3[11]};
			4'd3 : y3p = {y3[5], y3[4], y3[3], y3[2], y3[9], y3[14], y3[13], y3[12], y3[11], y3[6], y3[7], y3[8], y3[1], y3[15], y3[0], y3[10]};
			4'd4 : y3p = {y3[12], y3[11], y3[0], y3[7], y3[8], y3[5], y3[6], y3[15], y3[10], y3[13], y3[14], y3[1], y3[2], y3[3], y3[4], y3[9]};
			4'd5 : y3p = {y3[14], y3[0], y3[1], y3[2], y3[3], y3[9], y3[8], y3[7], y3[15], y3[5], y3[6], y3[13], y3[12], y3[11], y3[10], y3[4]};
			4'd6 : y3p = {y3[13], y3[12], y3[11], y3[10], y3[2], y3[7], y3[8], y3[9], y3[0], y3[14], y3[15], y3[3], y3[4], y3[5], y3[6], y3[1]};
			4'd7 : y3p = {y3[2], y3[9], y3[10], y3[11], y3[12], y3[7], y3[6], y3[5], y3[14], y3[3], y3[4], y3[0], y3[15], y3[1], y3[8], y3[13]};
			4'd8 : y3p = {y3[8], y3[7], y3[4], y3[3], y3[2], y3[13], y3[12], y3[11], y3[0], y3[9], y3[10], y3[14], y3[15], y3[6], y3[5], y3[1]};
			4'd9 : y3p = {y3[3], y3[2], y3[10], y3[11], y3[12], y3[5], y3[14], y3[0], y3[1], y3[4], y3[15], y3[6], y3[7], y3[8], y3[9], y3[13]};
			4'd10: y3p = {y3[2], y3[10], y3[6], y3[5], y3[4], y3[14], y3[13], y3[12], y3[11], y3[1], y3[0], y3[15], y3[9], y3[8], y3[7], y3[3]};
			4'd11: y3p = {y3[12], y3[11], y3[8], y3[1], y3[15], y3[3], y3[2], y3[9], y3[10], y3[13], y3[14], y3[4], y3[5], y3[6], y3[7], y3[0]};
			4'd12: y3p = {y3[8], y3[7], y3[0], y3[11], y3[12], y3[5], y3[6], y3[15], y3[14], y3[9], y3[10], y3[1], y3[2], y3[3], y3[4], y3[13]};
			4'd13: y3p = {y3[3], y3[2], y3[1], y3[0], y3[14], y3[9], y3[8], y3[7], y3[6], y3[4], y3[15], y3[13], y3[12], y3[11], y3[10], y3[5]};
			4'd14: y3p = {y3[2], y3[10], y3[11], y3[12], y3[13], y3[7], y3[8], y3[9], y3[15], y3[1], y3[0], y3[3], y3[4], y3[5], y3[6], y3[14]};
			4'd15: y3p = {y3[12], y3[11], y3[10], y3[9], y3[2], y3[7], y3[6], y3[5], y3[4], y3[13], y3[14], y3[0], y3[15], y3[1], y3[8], y3[3]};
			default: y3p = y3;
		endcase
	end

	// Bit gathers, transcribed from seibuspi_sprite_decrypt().
	wire [15:0] s1_in = {
		y1[13], y2[6], y2[15], y3p[12],  // bits 15..12
		y1[7], y2[0], y2[9], y3p[2],  // bits 11..8
		y3p[14], y1[1], y1[10], y2[3],  // bits 7..4
		y2[12], y3p[6], y3p[7], y1[4]  // bits 3..0
	};

	wire [15:0] add1_in = {
		keyf[2], keyf[3], keyf[8], keyf[9],  // bits 15..12
		addr[11], keyf[0], keyf[1], keyf[6],  // bits 11..8
		keyf[7], addr[11], addr[11], keyf[4],  // bits 7..4
		keyf[5], keyf[10], addr[10], addr[11]  // bits 3..0
	};

	wire [31:0] s2_in = {
		y1[14], y2[7], y3p[4], y3p[13],  // bits 31..28
		y1[8], y2[1], y2[10], y3p[1],  // bits 27..24
		y3p[10], y1[0], y1[9], y2[2],  // bits 23..20
		y2[11], y3p[15], y3p[8], y1[3],  // bits 19..16
		y1[12], y2[5], y2[14], y3p[11],  // bits 15..12
		y1[6], y1[15], y2[8], y3p[3],  // bits 11..8
		y3p[9], y1[2], y1[11], y2[4],  // bits 7..4
		y2[13], y3p[5], y3p[0], y1[5]  // bits 3..0
	};

	wire [31:0] add2_in = {
		keyf[0], keyf[8], keyf[1], keyf[9],  // bits 31..28
		keyf[2], keyf[10], keyf[3], addr[10],  // bits 27..24
		keyf[4], addr[11], keyf[5], addr[11],  // bits 23..20
		keyf[6], addr[11], keyf[7], addr[11],  // bits 19..16
		addr[11], addr[11], addr[11], addr[11],  // bits 15..12
		addr[10], keyf[10], keyf[9], keyf[8],  // bits 11..8
		keyf[7], keyf[6], keyf[5], keyf[4],  // bits 7..4
		keyf[3], keyf[2], keyf[1], keyf[0]  // bits 3..0
	};

