//============================================================================
//  SlopperPI - reset synchroniser
//
//  Brings an asynchronous reset level into a clock domain so that its
//  *deassertion* is synchronous to that clock.
//
//  This is not cosmetic. The core's reset is a mix of signals from three
//  domains -- RESET and the OSD bits arrive with clk_sys, and `rom_ready` is
//  generated by the ROM loader on clk_ram -- while z386 has parts that use a
//  genuine asynchronous clear (dsp_mul.sv:57, `always_ff @(posedge clk or
//  negedge reset_n)`). Feeding that directly produced a real recovery violation
//  from rom_loader|rom_ready to dsp_mul|acc[*], which in hardware means the CPU
//  can come out of reset part-way through a cycle and start from an
//  inconsistent state.
//
//  Assertion is delayed by STAGES cycles as well, which is harmless: every
//  reset source here is a level held for far longer than that.
//============================================================================

module spi_reset_sync #(parameter STAGES = 3)
(
	input      clk,
	input      rst_in,     // asynchronous, active high
	output     rst_out     // synchronous to clk, active high
);

	// The initial value is the power-up state Quartus programs into the flops, so
	// the domain starts held in reset rather than spending the first few cycles
	// released while rst_in propagates. Verilator flags the combination of an
	// initial value and a procedural assignment; here it is deliberate.
	/* verilator lint_off PROCASSINIT */
	(* preserve *) reg [STAGES-1:0] sr = {STAGES{1'b1}};
	/* verilator lint_on PROCASSINIT */

	always @(posedge clk) sr <= {sr[STAGES-2:0], rst_in};

	assign rst_out = sr[STAGES-1];

endmodule
