#!/usr/bin/env python3
"""
Generate the YMF271 fixed-point tables from MAME's rewritten OPX core.

MAME's core changed domain in 03761e46766 ("sound/ymf271: rewrite the YMF271
(OPX) core"). The old core worked in linear gains -- a 6 x 1024 signed waveform
ROM multiplied by an envelope volume -- and this script used to evaluate its
doubles ahead of time. The new core is OPM-shaped: everything is an attenuation
in 1/256ths of a decade, the operator is a log-sin lookup summed with the
envelope and resolved through one exponential, and the envelope counts upward
in attenuation units at fs/2. So the tables are different tables.

Two are computed (MAME builds them in init_tables from doubles):

  LOGSIN [256]     -log2(sin((i+0.5) * pi/512)) * 256, the quarter-sine
  EXP    [256]     2^(-(i+1)/256) * 2048, the shared exponential

The rest are literal C arrays and are scraped, so this file stays a derivation
of MAME rather than a second source of truth:

  EG_INC   [64]     nibble k of entry r = envelope increment for sub-step k
  RKS      [32][8]  rate key scaling (unchanged from the old core's RKS_Table)
  DETUNE   [32][4]  OPM DT1, in units of fs/2^20
  MODLVL   [8]      phase modulation depth, applied as (sum * lvl) >> 8
  PMS_K    [8]      LFO pitch depth, max deviation = fnum * k / 1024

Gone with the old core, and deliberately not replaced: WAVE (the operator is
a log-sin lookup now), PLFO / PLFO_W / ALFO_K (pitch and amplitude LFO are
arithmetic on fnum and on the attenuation, not gain tables), ENV_VOL, TL and
ATTEN (all three collapse into the attenuation sum and pan()), AR_STEP,
DC_STEP and DC_RECIP (the envelope is EG_INC now), LFO_STEP (a counter and a
divider), FBLVL (feedback is OPM's shift law).

That is a saving of about 130 Kbit of block RAM, which matters at 97% full.

The sound chip runs at its documented 16.9344 MHz on SXX2E, so fs is exactly
44100 and the envelope clock exactly 22050. Neither appears in these tables --
the new core's arithmetic is integer throughout and carries no rate term.

Usage:
    tools/gen_ymf271_tables.py [path/to/mame] > rtl/ymf271_tables.vh
"""

import math
import os
import re
import sys

DEFAULT_MAME = os.path.expanduser("~/proj/mame")

# The commit that introduced the core these tables describe. Named in the error
# path so a future MAME rewrite says which revision this script was written
# against instead of just failing to find a symbol.
CORE_COMMIT = "03761e46766"


def read_source(mame_root):
    path = os.path.join(mame_root, "src/devices/sound/ymf271.cpp")
    with open(path) as f:
        return f.read(), path


def parse_int_table(src, decl, count):
    """Flatten a C integer array initialiser. Handles hex and nested braces."""
    m = re.search(re.escape(decl) + r"\s*=\s*\{(.*?)\}\s*;", src, re.S)
    if not m:
        raise SystemExit(
            "could not find %s in ymf271.cpp -- these tables are generated from "
            "the OPX core introduced in MAME %s; if that core has been replaced "
            "again this script needs rewriting, not repointing."
            % (decl, CORE_COMMIT))
    vals = [int(t, 0) for t in re.findall(r"0[xX][0-9a-fA-F]+|-?\d+", m.group(1))]
    if len(vals) != count:
        raise SystemExit("%s has %d entries, expected %d" % (decl, len(vals), count))
    return vals


def emit(name, width, values, per_line, fmt):
    print("\t/* verilator lint_off UNUSEDPARAM */")
    print("\treg [%d:0] %s [0:%d];" % (width - 1, name, len(values) - 1))
    print("\t/* verilator lint_on UNUSEDPARAM */")
    print("\tinitial begin")
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        cells = []
        for j, v in enumerate(chunk):
            cells.append("%s[%3d] = %d'%s;" % (name, i + j, width, fmt % v))
        print("\t\t" + "  ".join(cells))
    print("\tend")
    print()


def bits(values):
    """Narrowest unsigned width that holds every value."""
    return max(1, max(values).bit_length())


def main():
    mame_root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MAME
    src, path = read_source(mame_root)

    eg_inc = parse_int_table(src, "const uint32_t eg_inc[64]", 64)
    rks = parse_int_table(src, "const uint8_t rks_tab[32][8]", 256)
    detune = parse_int_table(src, "const uint8_t detune_tab[32][4]", 128)
    modlvl = parse_int_table(src, "const uint16_t modlevel[8]", 8)
    pms_k = parse_int_table(src, "const uint8_t pms_k[8]", 8)

    # init_tables(), verbatim.
    logsin = [int(math.floor(-math.log(math.sin((i + 0.5) * math.pi / 512.0))
                             / math.log(2.0) * 256.0 + 0.5)) for i in range(256)]
    exp_t = [int(math.floor(math.pow(2.0, -(i + 1) / 256.0) * 2048.0 + 0.5))
             for i in range(256)]

    print("//==========================================================================")
    print("//  SeibuSPI - YMF271 fixed-point tables")
    print("//")
    print("//  GENERATED by tools/gen_ymf271_tables.py -- do not edit.")
    print("//  Source: %s" % path)
    print("//  Core:   MAME %s, the OPX rewrite" % CORE_COMMIT)
    print("//==========================================================================")
    print()

    print("\t// init_tables(): -log2(sin((i+0.5)*pi/512)) * 256, the quarter sine.")
    print("\t// Indexed by the folded phase; the operator adds the envelope")
    print("\t// attenuation to this sum and resolves it through YMF_EXP.")
    emit("YMF_LOGSIN", bits(logsin), logsin, 8, "d%d")

    print("\t// init_tables(): 2^(-(i+1)/256) * 2048. One exponential serves both")
    print("\t// the operator output and env_mul()'s PCM envelope multiply.")
    emit("YMF_EXP", bits(exp_t), exp_t, 8, "d%d")

    print("\t// eg_inc[rate]: nibble k is the envelope increment for EG sub-step k,")
    print("\t// k = (eg_cnt >> shift) & 7 below rate 48 and eg_cnt & 7 above it.")
    emit("YMF_EG_INC", 32, eg_inc, 4, "h%08X")

    print("\t// rks_tab[keycode][KS], flattened to {keycode[4:0], ks[2:0]}.")
    print("\t// Unchanged from the old core's RKS_Table.")
    emit("YMF_RKS", bits(rks), rks, 8, "d%d")

    print("\t// detune_tab[keycode][DT&3], flattened to {keycode[4:0], dt[1:0]},")
    print("\t// in units of fs/2^20 -- one LSB of a 20-bit phase increment.")
    emit("YMF_DETUNE", bits(detune), detune, 8, "d%d")

    print("\t// modlevel[FB of a modulated slot]: (14-bit modulator sum * this) >> 8.")
    emit("YMF_MODLVL", bits(modlvl), modlvl, 8, "d%d")

    print("\t// pms_k[PMS]: max LFO pitch deviation = fnum * k / 1024.")
    emit("YMF_PMS_K", bits(pms_k), pms_k, 8, "d%d")


if __name__ == "__main__":
    main()
