#!/usr/bin/env python3
"""
Extract MAME's Seibu decryption routines verbatim into a standalone C++ header
for use as a testbench reference.

The point is independence: tools/gen_spi_tables.py *parses* MAME to emit
Verilog, while this script *copies* MAME to emit the reference implementation.
If the two agree over random inputs, the parser is validated rather than merely
self-consistent.

Usage:
    tools/gen_ref_c.py [path/to/mame] > sim/spi_ref.h
"""

import re
import sys
import os

DEFAULT_MAME = os.path.expanduser("~/proj/mame")

PROLOGUE = r'''//============================================================================
//  SlopperPI - reference implementation for the decrypt testbenches.
//
//  GENERATED by tools/gen_ref_c.py -- do not edit.
//  Bodies below are copied verbatim from MAME.
//============================================================================
#pragma once

#include <cstdint>
#include <cstring>

typedef uint8_t  u8;
typedef uint16_t u16;
typedef uint32_t u32;

#define BIT(x, n) (((x) >> (n)) & 1u)

// MAME's bitswap<N>(val, b_{N-1}, ..., b_0): the first index listed supplies
// the result's most significant bit.
template <int N, typename T, typename... A>
static inline T bitswap(T val, A... a)
{
    const int idx[] = { a... };
    static_assert(sizeof(idx) / sizeof(int) == N, "bitswap arity mismatch");
    T r = 0;
    for (int i = 0; i < N; i++)
        r |= (T)(((val >> idx[i]) & 1u) << (N - 1 - i));
    return r;
}

'''


def grab(src, pattern, what, flags=re.S):
    m = re.search(pattern, src, flags)
    if not m:
        raise SystemExit("could not extract %s" % what)
    return m.group(0)


def main():
    mame = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MAME
    seibu_dir = os.path.join(mame, "src/mame/seibu")

    helper = open(os.path.join(seibu_dir, "seibu_helper.cpp")).read()
    spr    = open(os.path.join(seibu_dir, "seibuspi_m.cpp")).read()
    vid    = open(os.path.join(seibu_dir, "seibuspi_v.cpp")).read()

    out = [PROLOGUE]

    # --- seibu_helper.cpp -------------------------------------------------
    out.append(grab(
        helper,
        r"u32 seibu_partial_carry_sum\(u32 add1, u32 add2, u32 carry_mask, int bits\)\s*\{.*?\n\}",
        "seibu_partial_carry_sum"))
    out.append("""
static inline u32 seibu_partial_carry_sum16(u32 a, u32 b, u32 m) { return seibu_partial_carry_sum(a, b, m, 16); }
static inline u32 seibu_partial_carry_sum24(u32 a, u32 b, u32 m) { return seibu_partial_carry_sum(a, b, m, 24); }
static inline u32 seibu_partial_carry_sum32(u32 a, u32 b, u32 m) { return seibu_partial_carry_sum(a, b, m, 32); }
""")

    # --- seibuspi_v.cpp ---------------------------------------------------
    out.append(grab(
        vid,
        r"static u32 decrypt_tile\(u32 val, int tileno, u32 key1, u32 key2, u32 key3\)\s*\{.*?\n\}",
        "decrypt_tile"))

    # --- seibuspi_m.cpp ---------------------------------------------------
    out.append(grab(spr, r"static const u16 key_table\[256\]\s*=\s*\{.*?\n\};", "key_table"))
    out.append(grab(spr, r"static const u8 spi_bitswap\[16\]\[16\]\s*=\s*\{.*?\n\};", "spi_bitswap"))
    out.append(grab(spr, r"static int key\(int table,\s*int addr\)\s*\{.*?\n\}", "key()"))
    out.append(grab(
        spr,
        r"void seibuspi_sprite_decrypt\(u8 \*src, int rom_size\)\s*\{.*?\n\}",
        "seibuspi_sprite_decrypt"))

    print("\n\n".join(out))


if __name__ == "__main__":
    main()
