#!/usr/bin/env python3
"""
Generate the RISE10 sprite decryption constants from MAME's seibuspi_m.cpp.

RISE10 is much smaller than SEI252 -- one 32-bit bit permutation and four
constants, with no key table and no address term -- but the permutation is
still 32 hand-ordered numbers, and section 5.4 of PLAN.md is about what happens
when those are typed by hand: a silent error that shows up only as subtly
garbled sprites. So it is parsed, like everything else.

tools/gen_ref_c.py separately COPIES MAME's function for the testbench, so
agreement between the two validates this parser rather than being
self-consistent.

Usage:
    tools/gen_rise10_tables.py [path/to/mame] > rtl/spi_rise10_tables.vh
"""

import os
import re
import sys

DEFAULT_MAME = os.path.expanduser("~/proj/mame")


def grab_func(src):
    m = re.search(r"void seibuspi_rise10_sprite_decrypt\(u8 \*rom, int size\)\s*\{(.*?)\n\}",
                  src, re.S)
    if not m:
        raise SystemExit("could not find seibuspi_rise10_sprite_decrypt")
    return m.group(1)


def parse_bitswap(body):
    """The bitswap<32> argument list: 32 source bit numbers, MSB first.

    MAME's bitswap<32>(v, b31, b30, ... b0) takes the source bit for each
    destination bit starting at destination 31. So the Nth number listed is the
    source of destination bit 31-N.
    """
    m = re.search(r"bitswap<32>\(\s*.*?,\s*((?:\d+\s*,\s*)+\d+)\s*\)", body, re.S)
    if not m:
        raise SystemExit("could not find the bitswap<32> list")
    nums = [int(x) for x in re.findall(r"\d+", m.group(1))]
    if len(nums) != 32:
        raise SystemExit("expected 32 bitswap entries, got %d" % len(nums))
    if sorted(nums) != list(range(32)):
        raise SystemExit("bitswap list is not a permutation of 0..31")
    return nums


def parse_consts(body):
    """The two partial-carry sums and their xors."""
    m54 = re.search(r"plane54\s*=\s*seibu_partial_carry_sum16\(plane54,\s*"
                    r"(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+)\)\s*\^\s*(0x[0-9a-fA-F]+)", body)
    if not m54:
        raise SystemExit("could not parse the plane54 sum")
    # The addend is written as an xor of two literals in MAME; evaluate it.
    m3210 = re.search(r"plane3210\s*=\s*seibu_partial_carry_sum32\(plane3210,\s*"
                      r"([^,]+),\s*(0x[0-9a-fA-F]+)\)\s*\^\s*(0x[0-9a-fA-F]+)", body)
    if not m3210:
        raise SystemExit("could not parse the plane3210 sum")
    addend_expr = m3210.group(1).strip()
    if not re.fullmatch(r"[0-9a-fA-Fx\s^]+", addend_expr):
        raise SystemExit("unexpected plane3210 addend %r" % addend_expr)
    addend = eval(addend_expr, {"__builtins__": {}}, {})   # only hex and ^
    return (int(m54.group(1), 16), int(m54.group(2), 16), int(m54.group(3), 16),
            addend, int(m3210.group(2), 16), int(m3210.group(3), 16))


def main():
    mame = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MAME
    path = os.path.join(mame, "src/mame/seibu/seibuspi_m.cpp")
    body = grab_func(open(path).read())

    bs = parse_bitswap(body)
    a54, m54, x54, a3210, m3210, x3210 = parse_consts(body)

    o = []
    o.append("//" + "=" * 74)
    o.append("//  SeibuSPI - RISE10 sprite decryption constants")
    o.append("//")
    o.append("//  GENERATED by tools/gen_rise10_tables.py from")
    o.append("//  %s" % os.path.relpath(path, mame))
    o.append("//  Do not edit.")
    o.append("//")
    o.append("//  Unlike SEI252 there is no key table and no address term: every operand")
    o.append("//  below is a constant, which is why this unit needs no per-tile fetch.")
    o.append("//" + "=" * 74)
    o.append("")
    o.append("localparam [15:0] R10_ADD54    = 16'h%04X;" % a54)
    o.append("localparam [15:0] R10_MASK54   = 16'h%04X;" % m54)
    o.append("localparam [15:0] R10_XOR54    = 16'h%04X;" % x54)
    o.append("localparam [31:0] R10_ADD3210  = 32'h%08X;" % a3210)
    o.append("localparam [31:0] R10_MASK3210 = 32'h%08X;" % m3210)
    o.append("localparam [31:0] R10_XOR3210  = 32'h%08X;" % x3210)
    o.append("")
    o.append("// bitswap<32>: destination bit d takes source bit R10_BS[d].")
    o.append("// MAME lists the sources starting at destination 31, so the list is")
    o.append("// reversed here and indexed by destination.")
    src_by_dest = list(reversed(bs))
    o.append("// The argument must be a simple identifier: Verilog cannot index a")
    o.append("// parenthesised expression, so no (v) here.")
    o.append("`define R10_BITSWAP(v) { \\")
    # Build the concat MSB (dest 31) first, as Verilog concatenation expects.
    lines = []
    for d in range(31, -1, -1):
        lines.append("\tv[%2d]" % src_by_dest[d])
    for i in range(0, 32, 4):
        tail = " \\" if i + 4 < 32 else " }"
        o.append("\t" + ", ".join(x.strip() for x in lines[i:i + 4]) + "," * 0 +
                 ("," if i + 4 < 32 else "") + tail)
    print("\n".join(o))


if __name__ == "__main__":
    main()
