#!/usr/bin/env python3
"""
Turn a tools/mame_flash_raw.lua capture into sim/flash_replay.h.

The replay test in sim/tb_ymf271.cpp drives the wave-memory port with the
updater's REAL register writes rather than the datasheet's command sequence,
because the two are not the same shape: the address register runs one behind,
the 0x40 command goes through the same auto-incrementing port as the data, and
only the low address byte is rewritten before each datum (PLAN.md 19.11).

    SLOP_OUT=raw.txt mame rdft2 -autoboot_script tools/mame_flash_raw.lua ...
    tools/gen_flash_replay.py raw.txt rdft2_flash.bin 0x2900 > sim/flash_replay.h

The expected bytes come from the reference image, whose sha256 build_soundflash
checks against MAME's own nvram, so the test compares against MAME and not
against another copy of this core's arithmetic.
"""

import re
import sys


def main():
    if len(sys.argv) != 4:
        raise SystemExit(__doc__.strip())
    trace, image, base = sys.argv[1], sys.argv[2], int(sys.argv[3], 0)

    seq = []
    for line in open(trace):
        m = re.match(r"W ([0-9A-F]{2}) = ([0-9A-F]{2})", line.strip())
        if m:
            seq.append((int(m.group(1), 16), int(m.group(2), 16)))
    page = open(image, "rb").read()[base:base + 256]
    if len(page) != 256:
        raise SystemExit("%s has no page at %#x" % (image, base))

    w = sys.stdout.write
    w("//" + "=" * 74 + "\n")
    w("//  SlopperPI - one page of a flash update, captured off MAME's Z80.\n"
      "//\n"
      "//  GENERATED by tools/gen_flash_replay.py -- do not edit. Every write the\n"
      "//  Z80 makes to the YMF271's wave-memory registers for one flash page, in\n"
      "//  order, with the bytes MAME's flash holds afterwards.\n"
      "//\n"
      "//  This page is here because the core got it WRONG on hardware: one byte\n"
      "//  came back erased where MAME holds data, reproducibly, across two builds,\n"
      "//  with the accepted-program count matching MAME's issued-command count\n"
      "//  exactly (PLAN.md 19.11).\n")
    w("//" + "=" * 74 + "\n\n")
    w("// The chip is mid-session when the capture starts: the 0x40 for the first\n"
      "// byte of this page was written at REPLAY_BASE before the first line below.\n")
    w("static const uint32_t REPLAY_BASE = 0x%X;\n\n" % base)
    w("static const struct { unsigned char reg, val; } REPLAY[] = {\n")
    for i in range(0, len(seq), 6):
        w("    " + " ".join("{0x%02X,0x%02X}," % p for p in seq[i:i + 6]) + "\n")
    w("};\n\n")
    w("// MAME's flash, bytes 0x%X-0x%X, after the sequence above.\n"
      % (base, base + 255))
    w("static const unsigned char REPLAY_EXPECT[256] = {\n")
    for i in range(0, 256, 12):
        w("    " + " ".join("0x%02X," % b for b in page[i:i + 12]) + "\n")
    w("};\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
