#!/usr/bin/env python3
"""
Generate the SEI252 sprite decryption tables and bit-gather expressions
directly from MAME's seibu/seibuspi_m.cpp.

These tables are long and a silent transcription error shows up only as subtly
garbled sprites, so nothing here is typed by hand.

Usage:
    tools/gen_spi_tables.py [path/to/mame] > rtl/spi_spr_tables.vh
"""

import re
import sys
import os

DEFAULT_MAME = os.path.expanduser("~/proj/mame")


def read_source(mame_root):
    path = os.path.join(mame_root, "src/mame/seibu/seibuspi_m.cpp")
    with open(path) as f:
        return f.read(), path


def parse_key_table(src):
    m = re.search(r"static const u16 key_table\[256\]\s*=\s*\{(.*?)\};", src, re.S)
    if not m:
        raise SystemExit("could not find key_table")
    vals = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{4})", m.group(1))]
    if len(vals) != 256:
        raise SystemExit("key_table has %d entries, expected 256" % len(vals))
    return vals


def parse_bitswap(src):
    m = re.search(r"static const u8 spi_bitswap\[16\]\[16\]\s*=\s*\{(.*?)\n\};", src, re.S)
    if not m:
        raise SystemExit("could not find spi_bitswap")
    rows = re.findall(r"\{([^{}]*?)\}", m.group(1))
    if len(rows) != 16:
        raise SystemExit("spi_bitswap has %d rows, expected 16" % len(rows))
    table = []
    for r in rows:
        ent = [int(v) for v in re.findall(r"\d+", r)]
        if len(ent) != 16:
            raise SystemExit("spi_bitswap row has %d entries, expected 16" % len(ent))
        table.append(ent)
    return table


TERM = re.compile(
    r"\(\s*(?:"
    r"BIT\(\s*(?P<var>y1|y2|y3|addr)\s*,\s*(?P<bit>\d+)\s*\)"
    r"|key\(\s*(?P<kt>\d+)\s*,\s*addr\s*\)"
    r")\s*<<\s*(?P<pos>\d+)\s*\)"
)


def parse_gather(src, name, width):
    """Parse `u32 <name> = (BIT(..) << n) | ... ;` into a list of Verilog terms
    indexed by destination bit."""
    m = re.search(r"u32\s+%s\s*=\s*(.*?);" % re.escape(name), src, re.S)
    if not m:
        raise SystemExit("could not find %s" % name)
    body = m.group(1)

    slots = [None] * width
    n = 0
    for t in TERM.finditer(body):
        pos = int(t.group("pos"))
        if pos >= width:
            raise SystemExit("%s: bit %d out of range" % (name, pos))
        if slots[pos] is not None:
            raise SystemExit("%s: bit %d assigned twice" % (name, pos))
        if t.group("var"):
            # y3 is used *after* the permutation, so it refers to y3p in the RTL.
            var = "y3p" if t.group("var") == "y3" else t.group("var")
            slots[pos] = "%s[%s]" % (var, t.group("bit"))
        else:
            slots[pos] = "keyf[%s]" % t.group("kt")
        n += 1

    missing = [i for i, s in enumerate(slots) if s is None]
    if missing:
        raise SystemExit("%s: bits %s not assigned" % (name, missing))
    if n != width:
        raise SystemExit("%s: %d terms for %d bits" % (name, n, width))
    return slots


def emit_concat(name, slots, width, indent="\t"):
    """Emit `wire [W-1:0] name = { msb, ..., lsb };` with the terms in
    descending bit order, wrapped for readability."""
    terms = list(reversed(slots))
    out = ["%swire [%d:0] %s = {" % (indent, width - 1, name)]
    for i in range(0, width, 4):
        chunk = ", ".join(terms[i:i + 4])
        comment = "  // bits %d..%d" % (width - 1 - i, max(0, width - 4 - i))
        sep = "," if i + 4 < width else ""
        out.append("%s\t%s%s%s" % (indent, chunk, sep, comment))
    out.append("%s};" % indent)
    return "\n".join(out)


def main():
    mame_root = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MAME
    src, path = read_source(mame_root)

    key_table = parse_key_table(src)
    bitswap = parse_bitswap(src)
    s1 = parse_gather(src, "s1", 16)
    add1 = parse_gather(src, "add1", 16)
    s2 = parse_gather(src, "s2", 32)
    add2 = parse_gather(src, "add2", 32)

    o = []
    w = o.append
    w("//" + "=" * 74)
    w("//  SeibuSPI - SEI252 sprite decryption tables")
    w("//")
    w("//  GENERATED by tools/gen_spi_tables.py -- do not edit.")
    w("//  Source: %s" % path.replace(os.path.expanduser("~"), "~"))
    w("//" + "=" * 74)
    w("")

    # ---- key_table -------------------------------------------------------
    w("\t// key_table[256], indexed by addr[7:0].")
    w("\treg [15:0] key_table [0:255];")
    w("\tinitial begin")
    for i in range(0, 256, 4):
        row = "  ".join("key_table[%3d] = 16'h%04X;" % (i + j, key_table[i + j])
                        for j in range(4))
        w("\t\t" + row)
    w("\tend")
    w("")

    # ---- bitswap permutation --------------------------------------------
    # MAME: bitswap<16>(y3, bs[0], ..., bs[15]) puts y3[bs[0]] in result bit 15,
    # so result[j] = y3[bs[15-j]].
    w("\t// y3 permutation, selected by key_table[addr[7:0]][3:0].")
    w("\t// MAME bitswap<16>(y3, bs[0]..bs[15]) => result[j] = y3[bs[15-j]].")
    w("\treg [15:0] y3p;")
    w("\talways @* begin")
    w("\t\tcase (bsidx)")
    for idx, bs in enumerate(bitswap):
        terms = ", ".join("y3[%d]" % bs[15 - j] for j in range(15, -1, -1))
        w("\t\t\t4'd%-2d: y3p = {%s};" % (idx, terms))
    w("\t\t\tdefault: y3p = y3;")
    w("\t\tendcase")
    w("\tend")
    w("")

    # ---- gathers ---------------------------------------------------------
    w("\t// Bit gathers, transcribed from seibuspi_sprite_decrypt().")
    w(emit_concat("s1_in", s1, 16))
    w("")
    w(emit_concat("add1_in", add1, 16))
    w("")
    w(emit_concat("s2_in", s2, 32))
    w("")
    w(emit_concat("add2_in", add2, 32))
    w("")

    print("\n".join(o))


if __name__ == "__main__":
    main()
